package practica3;

import java.awt.Color;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

public class VentanaMiller extends javax.swing.JFrame {

    public VentanaMiller() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
    public static int MillerRabin(BigInteger p, int rondas){
        int u = 0;
        BigInteger s, a;
        ArrayList<BigInteger> Lista = new ArrayList();
        boolean esPrimo, salida;
        Random aleatorio = new Random();
        int primo = 0;
        int contador;

        if (p.mod(new BigInteger("2")).equals(new BigInteger("0"))) {
            return -1;
        } else {
            
            BigInteger Par = p.subtract(new BigInteger("1"));
            boolean salir = false;
            s = Par;
            for (int i = 0; salir == false;) {
                
                if (Par.mod(new BigInteger("2")).equals(new BigInteger("0"))) {
                    Par = Par.divide(new BigInteger("2"));
                    i++;
                } else {
                    s = Par;
                    salir = true;
                }
                u = i;
            }

            a = new BigInteger("0");

            if (!(p.subtract(new BigInteger("3")).compareTo(new BigInteger("20")) == 1)) {
                
                rondas = p.intValue() - 4;
            }
            for (contador = 0; contador < rondas; contador++) {
               
                salida = true;
                while (!(a.compareTo(new BigInteger("1")) == 1 && a.compareTo(p.subtract(new BigInteger("1"))) == -1)) {
                    a = new BigInteger(600, aleatorio);
                    a = a.mod(p.subtract(new BigInteger("2")));
                    
                    if (!Lista.isEmpty()) {
                        if (Lista.indexOf(a) != -1) {
                            a = new BigInteger("0");
                        }
                    }
                }
                Lista.add(a);
                
                a = a.modPow(s, p);
                
                if (a.equals(new BigInteger("1")) || a.equals(new BigInteger("-1"))) {
                    primo++;
                } else if (!a.equals(p.subtract(new BigInteger("1")))) {

                    esPrimo = false;
                    for (int i = 1; i <= u - 1;) {

                        if (a.equals(p.subtract(new BigInteger("1")))) {

                            salida = false;
                            i = u + 1;

                        }
                        a = a.modPow(new BigInteger("2"), p);

                        if (a.equals(p.subtract(new BigInteger("1")))) {

                            salida = false;
                            i = u + 1;
                        }

                        if (a.equals(new BigInteger("1")) && salida == true){
                            return 0;
                        } else if (a.equals(new BigInteger("-1")) && salida == true) {
                            primo++;
                            esPrimo = true;
                        } else {
                            i++;
                        }
                    }
                    if (esPrimo == false && salida == true) {
                        return 0;
                    }
                }
            }
            
            return 1;
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textComprobar = new javax.swing.JTextField();
        textRondas = new javax.swing.JTextField();
        botonComprobar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Numero a comprobar:");

        jLabel2.setText("Numero de rondas:");

        textComprobar.setForeground(new java.awt.Color(153, 153, 153));
        textComprobar.setText("Numero");
        textComprobar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textComprobarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textComprobarMousePressed(evt);
            }
        });
        textComprobar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textComprobarFocusGained(evt);
            }
        });

        textRondas.setForeground(new java.awt.Color(153, 153, 153));
        textRondas.setText("Rondas");
        textRondas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textRondasMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textRondasMousePressed(evt);
            }
        });
        textRondas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textRondasFocusGained(evt);
            }
        });

        botonComprobar.setText("Comprobar");
        botonComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprobarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textComprobar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(textRondas)))
                    .addComponent(botonComprobar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textComprobar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textRondas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonComprobar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprobarActionPerformed
        int res = MillerRabin(new BigInteger(textComprobar.getText().toString()), Integer.parseInt(textRondas.getText().toString()));
     
        if(res == 1)
            JOptionPane.showMessageDialog(this, "El numero es primo");
        else if(res == 0 || res == -1)
            JOptionPane.showMessageDialog(this, "El numero no es primo");
    }//GEN-LAST:event_botonComprobarActionPerformed

    private void textComprobarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textComprobarMouseClicked
        textComprobar.setText("");
        textComprobar.setForeground(Color.BLACK);
    }//GEN-LAST:event_textComprobarMouseClicked

    private void textComprobarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textComprobarMousePressed
        textComprobar.setText("");
        textComprobar.setForeground(Color.BLACK);
    }//GEN-LAST:event_textComprobarMousePressed

    private void textRondasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textRondasMouseClicked
        textRondas.setText("");
        textRondas.setForeground(Color.BLACK);
    }//GEN-LAST:event_textRondasMouseClicked

    private void textRondasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textRondasMousePressed
        textRondas.setText("");
        textRondas.setForeground(Color.BLACK);
    }//GEN-LAST:event_textRondasMousePressed

    private void textComprobarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textComprobarFocusGained
        textComprobar.setText("");
        textComprobar.setForeground(Color.BLACK);
    }//GEN-LAST:event_textComprobarFocusGained

    private void textRondasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textRondasFocusGained
        textRondas.setText("");
        textRondas.setForeground(Color.BLACK);
    }//GEN-LAST:event_textRondasFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonComprobar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField textComprobar;
    private javax.swing.JTextField textRondas;
    // End of variables declaration//GEN-END:variables
}
