package practica3;

import java.awt.Color;
import java.io.*;
import java.math.BigInteger;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class VentanaCifrado extends javax.swing.JFrame {

    private BigInteger p;
    private BigInteger q;
    private BigInteger n;
    private BigInteger phi;
    private BigInteger e;
    private BigInteger m;
    private Random aleatorio;
    private String textoSelec;
    
    
    public VentanaCifrado() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        aleatorio = new Random();
        //p = new BigInteger("383");
        //q = new BigInteger("881");
        n = new BigInteger("0");
        phi = new BigInteger("0");
        //e = new BigInteger("17");
        m = new BigInteger("0");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonGeneraClaves = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        textMensaje = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JScrollPane = new javax.swing.JScrollPane();
        mensajeCifrado = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        textMensajeDes = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensajeDescifrado = new javax.swing.JList();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Generación de Claves"));

        botonGeneraClaves.setText("Generar Claves");
        botonGeneraClaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGeneraClavesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonGeneraClaves)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonGeneraClaves)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cifrado"));

        textMensaje.setForeground(new java.awt.Color(153, 153, 153));
        textMensaje.setText("Introducir Texto");
        textMensaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textMensajeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textMensajeMousePressed(evt);
            }
        });

        jButton1.setText("Cifrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Texto cifrado:");

        jLabel3.setText("(Seleccionar el texto -> Ctrl+C para copiar)");

        JScrollPane.setViewportView(mensajeCifrado);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(textMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(JScrollPane))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Descifrado"));

        textMensajeDes.setForeground(new java.awt.Color(153, 153, 153));
        textMensajeDes.setText("Introducir Texto");
        textMensajeDes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textMensajeDesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textMensajeDesMousePressed(evt);
            }
        });

        jButton2.setText("Descifrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Texto descifrado:");

        jLabel4.setText("(Ctrl+V para pegar)");

        jScrollPane1.setViewportView(mensajeDescifrado);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(textMensajeDes, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMensajeDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21)))
                .addContainerGap())
        );

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGeneraClavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGeneraClavesActionPerformed
        boolean salir = false;
        int miller = 0;
        
        p = new BigInteger(100, aleatorio);
        while(!salir){
            
            miller = VentanaMiller.MillerRabin(p, 60);
            if(miller == 1)
                salir = true;
            else if(miller == 0 || miller == -1)
                p = p.subtract(BigInteger.ONE);
        }
        
        miller = 0; salir = false;
        
        q = new BigInteger(100, aleatorio);
        while(!salir){
            
            miller = VentanaMiller.MillerRabin(q, 60);
            if(miller == 1)
                salir = true;
            else if(miller == 0 || miller == -1)
                q = q.subtract(BigInteger.ONE);
        }
        
        n = p.multiply(q);
        
        phi = p.subtract(new BigInteger("1")).multiply(q.subtract(new BigInteger("1")));
        
        salir = false; miller = 0;
        e = new BigInteger(100, aleatorio);
        
        while(!salir){
            miller = VentanaMiller.MillerRabin(q, 60);
            if(miller == 1){
                if(e.gcd(phi).compareTo(BigInteger.ONE) == 0)
                    salir = true;
                else
                    e = e.subtract(BigInteger.ONE);      
            }
            else if(miller == 0 || miller == -1)
                q = q.subtract(BigInteger.ONE); 
        }
        
        
        
        PrintWriter fichPublica = null;
        try {
            fichPublica = new PrintWriter( new BufferedWriter(new FileWriter("clavepublica.txt")) );
        } catch (IOException ex) {
            Logger.getLogger(VentanaCifrado.class.getName()).log(Level.SEVERE, null, ex);
        }
        fichPublica.println("Clave publica");
        fichPublica.println("n");
        fichPublica.println(n);
        fichPublica.println("e");
        fichPublica.println(e);
        fichPublica.close();
        
        
        BigInteger privada = new BigInteger(e.toString());
        
        privada = privada.modInverse(phi);
        
        PrintWriter fichPrivada = null;
        try {
            fichPrivada = new PrintWriter( new BufferedWriter(new FileWriter("claveprivada.txt")) );
        } catch (IOException ex) {
            Logger.getLogger(VentanaCifrado.class.getName()).log(Level.SEVERE, null, ex);
        }
        fichPrivada.println("Clave privada");
        fichPrivada.println(privada);
        fichPrivada.close();
        
        JOptionPane.showMessageDialog(this, "Claves generadas en la ubicacion del programa", "Claves generadas", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_botonGeneraClavesActionPerformed

    private void textMensajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textMensajeMouseClicked
        textMensaje.setText("");
        textMensaje.setForeground(Color.black);
    }//GEN-LAST:event_textMensajeMouseClicked

    private void textMensajeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textMensajeMousePressed
        textMensaje.setText("");
        textMensaje.setForeground(Color.black);
    }//GEN-LAST:event_textMensajeMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        BufferedReader pub = null;
        try {
            pub = new BufferedReader(new FileReader("clavepublica.txt"));
            pub.readLine();
            pub.readLine();
            n = new BigInteger(pub.readLine().toString());
            pub.readLine();
            e = new BigInteger(pub.readLine().toString());
            pub.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VentanaCifrado.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (IOException ex) {
            Logger.getLogger(VentanaCifrado.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        
        BigInteger base = new BigInteger(textMensaje.getText().toString());
        BigInteger cifrado = base.modPow(e, n);
        
        
        DefaultListModel m = new DefaultListModel();
        m.add(0, cifrado.toString());
        this.mensajeCifrado.setModel(m);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textMensajeDesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textMensajeDesMouseClicked
        textMensajeDes.setText("");
        textMensajeDes.setForeground(Color.black);
    }//GEN-LAST:event_textMensajeDesMouseClicked

    private void textMensajeDesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textMensajeDesMousePressed
        textMensajeDes.setText("");
        textMensajeDes.setForeground(Color.black);
    }//GEN-LAST:event_textMensajeDesMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        BigInteger privada = new BigInteger("0");
        
        BufferedReader fichPri = null;
        try {
            fichPri = new BufferedReader(new FileReader("claveprivada.txt"));
            fichPri.readLine();
            privada = new BigInteger(fichPri.readLine());
            fichPri.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VentanaCifrado.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(VentanaCifrado.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        BigInteger base = new BigInteger(textMensajeDes.getText().toString());
        
        BigInteger descifrado = base.modPow(privada, n);
        //textDesc.setText(descifrado.toString());
        
        DefaultListModel m = new DefaultListModel();
        m.add(0, descifrado.toString());
        this.mensajeDescifrado.setModel(m);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JButton botonGeneraClaves;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList mensajeCifrado;
    private javax.swing.JList mensajeDescifrado;
    private javax.swing.JTextField textMensaje;
    private javax.swing.JTextField textMensajeDes;
    // End of variables declaration//GEN-END:variables
}
